### ISSUE TITLE
Regarding the storage location of demo data

### ISSUE THREAD

**Issue by sd68515** [WenjunZHAOwO/OT-Velocity#1]
I hope this message finds you well. I am currently working on reproducing the results from your paper and am facing some confusion regarding the proper placement of the data after downloading it. Could you kindly clarify the following points for me?

1. For the demo script data: Should I download the contents of 
 ‘./cardamom/tree/main/results_article/Benchmark_on_simulated_data ’ and place them directly into the .\OT-Velocity\Data\ folder as is?

2. For the curated dataset: Is it correct to simply copy all the .inputs\Curated folders from the BEELINE-data.zip archive into the .\OT-Velocity\Data\Curated folder?

3. For the real data set: Should I place the file single_cell_kouno_data.xlsx from the .\SINCERITIES-Matlab_ v2.0\THP1 data folder into the .\OT-Velocity\Data directory?

Your guidance would be greatly appreciated, as it would help ensure that I am correctly following the data organization structure required for the demo. Thank you in advance for your time and support.

Best regards,

**Comment by WenjunZHAOwO** [comment]
Thank you for your email. Looks correct to me. For the data from cardamom:
if you also use signed ground truth network, it might be missing those
files, which I reproduced according to the left panel of Figure 1 in
https://www.biorxiv.org/content/10.1101/2022.06.19.496754v3.full.pdf. If
you are unsure how to proceed, please send me a further individual email
and I will follow up with you.

**Comment by sd68515** [comment]
Thank you for your reply. I would like to confirm with you further about the use of cardamom project data.
Q1:
I've copied the BN8, CN5, FN4, FN8, and Trees* folders from the original project into .\OT-Velocity\Data\. Can I just run the relevant script directly, or do I need to do something else first?

Q2:
I'm currently working on running demo.ipynb, but I don't have the 'inter_signed.npy' file that the code seems to require. I've looked through the code in other files, but I can't find any mention of how to generate this file. Could you help me understand where this file comes from or how I can create it?

```
example = 'FN8'
FileName = '../Data/HARISSA/'+example+'/True/inter_signed.npy'
truth = np.load(FileName)
```

Thanks again.

**Comment by WenjunZHAOwO** [comment]
Q1: Under Data/ folder, create another folder named HARISSA and put all the
folders you mentioned in there. The inference should run and results will
automatically be saved.

Q2: That was what I mentioned in my previous email about the signed ground
truth. Basically inter_signed.npy files are similar to inter_x.npy files,
which are included in the data folder and indicate connectivity in the true
network. I further included the sign of ground truth based on the figure in
the paper I mentioned earlier (in the matrices, assign green edges to 1 and
red edges to -1). Those files are necessary only for signed prediction
(signed AUPRC and AUROC values, specifically).

And the BEELINE example should run without creating any additional files.

**Comment by sd68515** [comment]
I apologize for the delayed response, and I really appreciate your patience.
I plan to create the inter_signed.npy file based on the inter_x.npy file by reading the connectivity matrix from inter_x.npy, and then manually assigning activation and inhibition relationships as 1 and -1, respectively, following the method described by the CARDAMOM authors in Figure 1. Could you kindly confirm if this approach is correct?
Thank you.

**Comment by WenjunZHAOwO** [comment]
No worries, sounds correct to me. Please also feel free to email me
directly at ***@***.*** so I can share files with you.

**Comment by sd68515** [comment]
🥹So sweet. It looks like the email address provided has been privacy-protected (***@***.****). If possible, could you kindly email me at sd68515@foxmail.com? Thanks again for your assistance!
